import type { Metadata } from "next";
import "./globals.css";
import SessionProviderComponent from "@/providers/session-provider";
import { Toaster } from "@/components/ui/sonner";

export const metadata: Metadata = {
  title: "AuthJs in Nextjs",
  description: "Generated by codecrafthub.site",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <SessionProviderComponent>
          <Toaster />
          {children}
        </SessionProviderComponent>
      </body>
    </html>
  );
}
